version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "${CLICKHOUSE_PORT_HTTP}:8123"
      - "${CLICKHOUSE_PORT_NATIVE}:9000"
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    env_file:
      - .env  # Перенесено внутрь сервиса

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    env_file:
      - .env

  grafana:
    image: grafana/grafana:latest
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - .env

  api-tracker:
    build: .
    ports:
      - "${API_TRACKER_PORT}:8080"
    environment:
      - CLICKHOUSE_ADDR=clickhouse:9000
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - PROMETHEUS_PORT=${METRICS_PORT}
    depends_on:
      - clickhouse
      - prometheus
    env_file:
      - .env

volumes:
  clickhouse_data:
  grafana_data: