{
 "title": "Path and method",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Number of requests by hour for different paths",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    toStartOfHour(timestamp) AS \"Hour\",\r\n    path AS \"Endpoint\",\r\n    count(*) AS \"Request Count\"\r\nFROM api_logs.api_request_logs\r\nGROUP BY \"Hour\", path\r\nORDER BY \"Hour\"",
     "rawQuery": "/* grafana dashboard=Path and method, user=1 */\nSELECT\r\n    toStartOfHour(timestamp) AS \"Hour\",\r\n    path AS \"Endpoint\",\r\n    count(*) AS \"Request Count\"\r\nFROM api_logs.api_request_logs\r\nGROUP BY \"Hour\", path\r\nORDER BY \"Hour\"",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of endpoints requests",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "api_logs",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    path AS \"Endpoint\",\r\n    count(*) AS \"Request Count\"\r\nFROM api_logs.api_request_logs\r\nGROUP BY path\r\nORDER BY \"Request Count\" DESC",
     "rawQuery": "/* grafana dashboard=New dashboard, user=1 */\nSELECT\r\n    path AS \"Endpoint\",\r\n    count(*) AS \"Request Count\"\r\nFROM api_logs.api_request_logs\r\nGROUP BY path\r\nORDER BY \"Request Count\" DESC",
     "round": "0s",
     "table": "api_request_logs"
    }
   ]
  },
  {
   "title": "Average response time by path",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "api_logs",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    path AS \"Endpoint\",\r\n    avg(latency_ms) AS \"Average Latency (ms)\"\r\nFROM api_logs.api_request_logs\r\nGROUP BY path\r\nORDER BY \"Average Latency (ms)\" DESC",
     "rawQuery": "/* grafana dashboard=New dashboard, user=1 */\nSELECT\r\n    path AS \"Endpoint\",\r\n    avg(latency_ms) AS \"Average Latency (ms)\"\r\nFROM api_logs.api_request_logs\r\nGROUP BY path\r\nORDER BY \"Average Latency (ms)\" DESC",
     "round": "0s",
     "table": "api_request_logs"
    }
   ]
  },
  {
   "title": " Distribution by HTTP statuses for different methods",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "api_logs",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    method AS \"Method\",\r\n    status_code AS \"Status\",\r\n    count(*) AS \"Request Count\"\r\nFROM api_logs.api_request_logs\r\nGROUP BY method, status_code\r\nORDER BY \"Request Count\" DESC\r\n",
     "rawQuery": "/* grafana dashboard=New dashboard, user=1 */\nSELECT\r\n    method AS \"Method\",\r\n    status_code AS \"Status\",\r\n    count(*) AS \"Request Count\"\r\nFROM api_logs.api_request_logs\r\nGROUP BY method, status_code\r\nORDER BY \"Request Count\" DESC",
     "round": "0s",
     "table": "api_request_logs"
    }
   ]
  }
 ]
}